In [15]:
import dask.dataframe as dd
import pandas as pd

In [22]:
#convert file from utf-16 BOM to utf-8
filename = r"C:\Users\Maxime\Documents\Client\Irstea\TXM760\20200908-174605.head.csv"
with open(filename, 'r',encoding='utf-16') as source_file:
  with open("20200908-174605.utf8.csv", 'w+b') as dest_file:
    for line in source_file:
        dest_file.write(line.encode('utf-8'))

In [28]:
csv_headers = ['channel','time','utime','replica','background','duration','maxArea','minArea',
               'protocol','threshold','thresholdHigh','thresholdLow','timebin','condition','specie',
               'inadur','inadist','inact','smldur','smldist','smlct','lardur','lardist','larct','emptydur','emptyct']


#df = dd.read_csv("20200908-174605.utf8.csv",sep='\t')
df = pd.read_csv("20200910-113743.xls",encoding='utf16',sep='\t')

In [29]:
df.head()

,sn,datatype,location,animal,aname,areaid,timebinid,pn,start,end,...,inasmlthr,jitter,outSideOnError,burstthr,freezthr,chronolog,dose,etude,lot,Unnamed: 63
0,1,Locomotion,G01,16,A01,300,1,1,0.0,20.0,...,0,0,0,2000.0,500.0,0.0,0.01mg/L,ETUDE001,Pb,NaN
1,1,Locomotion,R01,32,A01,100,1,1,0.0,20.0,...,0,0,0,NaN,NaN,NaN,0.01mg/L,ETUDE001,Pb,NaN
2,1,Locomotion,R02,33,A02,101,1,1,0.0,20.0,...,0,0,0,NaN,NaN,NaN,0.01mg/L,ETUDE001,Pb,NaN
3,1,Locomotion,R03,34,A03,102,1,1,0.0,20.0,...,0,0,0,NaN,NaN,NaN,0.01mg/L,ETUDE001,Pb,NaN
4,1,Locomotion,R04,35,A04,103,1,1,0.0,20.0,...,0,0,0,NaN,NaN,NaN,0.01mg/L,ETUDE001,Pb,NaN

In [30]:
# Only selection datatype
df = df[df.datatype == 'Locomotion']
df.head()

,sn,datatype,location,animal,aname,areaid,timebinid,pn,start,end,...,inasmlthr,jitter,outSideOnError,burstthr,freezthr,chronolog,dose,etude,lot,Unnamed: 63
0,1,Locomotion,G01,16,A01,300,1,1,0.0,20.0,...,0,0,0,2000.0,500.0,0.0,0.01mg/L,ETUDE001,Pb,NaN
1,1,Locomotion,R01,32,A01,100,1,1,0.0,20.0,...,0,0,0,NaN,NaN,NaN,0.01mg/L,ETUDE001,Pb,NaN
2,1,Locomotion,R02,33,A02,101,1,1,0.0,20.0,...,0,0,0,NaN,NaN,NaN,0.01mg/L,ETUDE001,Pb,NaN
3,1,Locomotion,R03,34,A03,102,1,1,0.0,20.0,...,0,0,0,NaN,NaN,NaN,0.01mg/L,ETUDE001,Pb,NaN
4,1,Locomotion,R04,35,A04,103,1,1,0.0,20.0,...,0,0,0,NaN,NaN,NaN,0.01mg/L,ETUDE001,Pb,NaN

In [33]:
df = df.sort_values(by=['sn','pn','location','aname'])
df.head()

,sn,datatype,location,animal,aname,areaid,timebinid,pn,start,end,...,inasmlthr,jitter,outSideOnError,burstthr,freezthr,chronolog,dose,etude,lot,Unnamed: 63
42,1,Locomotion,E01,0,A01,500,1,1,0.0,20.0,...,0,0,0,2000.0,500.0,0.0,0.01mg/L,ETUDE001,Pb,NaN
44,1,Locomotion,E02,1,A02,501,1,1,0.0,20.0,...,0,0,0,2000.0,500.0,0.0,0.01mg/L,ETUDE001,Pb,NaN
66,1,Locomotion,E03,2,A03,502,1,1,0.0,20.0,...,0,0,0,2000.0,500.0,0.0,0.01mg/L,ETUDE001,Pb,NaN
67,1,Locomotion,E04,3,A04,503,1,1,0.0,20.0,...,0,0,0,2000.0,500.0,0.0,0.01mg/L,ETUDE001,Pb,NaN
68,1,Locomotion,E05,4,B01,504,1,1,0.0,20.0,...,0,0,0,2000.0,500.0,0.0,0.01mg/L,ETUDE001,Pb,NaN

In [34]:
df['time'] = df['stdate'] + " " + df['sttime']
df['time'].head()

42    10/09/2020 11:37:27
44    10/09/2020 11:37:27
66    10/09/2020 11:37:27
67    10/09/2020 11:37:27
68    10/09/2020 11:37:27
Name: time, dtype: object

In [59]:
# mapping = dict(enumerate([2,5,6,8,12,16,26,32]))
# df['D'] = df['A'].map(mapping)
#loc_to_specie = { 'E': 'Erpobdella', 'G': 'Gammarus', 'R': 'Radix' }
mapping = lambda a : { 'E': 'Erpobdella', 'G': 'Gammarus', 'R': 'Radix' }[a[0]]
#df['specie'] = loc_to_specie[df.location.astype(str).str[0]].astype(str) #loc_to_specie[df['location'][0]]
df['specie'] = df['location'].map(mapping)
df['utime'] = pd.to_datetime(df['time']).astype('int64')//1e9
df['replica'] = df['animal']
df['timebin'] = df['end'] - df['start']
df['condition'] = u"%s_%s_%s" % (df['etude'],df['dose'],df['lot'])
df.head(17)

,sn,datatype,location,animal,aname,areaid,timebinid,pn,start,end,...,dose,etude,lot,Unnamed: 63,time,specie,utime,replica,timebin,condition
42,1,Locomotion,E01,0,A01,500,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Erpobdella,1.602243e+09,0,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...
44,1,Locomotion,E02,1,A02,501,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Erpobdella,1.602243e+09,1,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...
66,1,Locomotion,E03,2,A03,502,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Erpobdella,1.602243e+09,2,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...
67,1,Locomotion,E04,3,A04,503,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Erpobdella,1.602243e+09,3,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...
68,1,Locomotion,E05,4,B01,504,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Erpobdella,1.602243e+09,4,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...
69,1,Locomotion,E06,5,B02,505,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Erpobdella,1.602243e+09,5,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...
70,1,Locomotion,E07,6,B03,506,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Erpobdella,1.602243e+09,6,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...
71,1,Locomotion,E08,7,B04,507,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Erpobdella,1.602243e+09,7,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...
72,1,Locomotion,E09,8,C01,508,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Erpobdella,1.602243e+09,8,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...
73,1,Locomotion,E10,9,C02,509,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Erpobdella,1.602243e+09,9,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...
74,1,Locomotion,E11,10,C03,510,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Erpobdella,1.602243e+09,10,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...
75,1,Locomotion,E12,11,C04,511,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Erpobdella,1.602243e+09,11,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...
76,1,Locomotion,E13,12,D01,512,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Erpobdella,1.602243e+09,12,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...
77,1,Locomotion,E14,13,D02,513,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Erpobdella,1.602243e+09,13,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...
78,1,Locomotion,E15,14,D03,514,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Erpobdella,1.602243e+09,14,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...
79,1,Locomotion,E16,15,D04,515,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Erpobdella,1.602243e+09,15,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...
0,1,Locomotion,G01,16,A01,300,1,1,0.0,20.0,...,0.01mg/L,ETUDE001,Pb,NaN,10/09/2020 11:37:27,Gammarus,1.602243e+09,16,20.0,42 ETUDE001\n44 ETUDE001\n66 ETUDE...

In [47]:
#df.drop(['specie1'],axis=1)

KeyError: "['specie1'] not found in axis"